from typing import List, Optional, Literal
from pydantic import BaseModel, Field

class UserQuery(BaseModel):
    """Input query from the user."""
    query_text: str = Field(..., description="The user's question.")
    user_role: Optional[str] = Field(None, description="The role of the user asking (e.g., 'developer', 'hr_manager').")

class RoutingDecision(BaseModel):
    """Decision on which specialist agent to route the query to."""
    department: Literal["HR", "TECH", "GENERAL"] = Field(..., description="The target department for the query.")
    reasoning: str = Field(..., description="Explanation for why this department was chosen.")
    confidence: float = Field(..., description="Confidence score between 0.0 and 1.0.")

class AgentResponse(BaseModel):
    """Response from a specialist agent."""
    answer: str = Field(..., description="The answer generated by the agent.")
    sources: List[str] = Field(default_factory=list, description="List of source document names used.")
    agent_name: str = Field(..., description="Name of the agent that generated the response.")

class AuditResult(BaseModel):
    """Result from the auditor agent."""
    is_safe: bool = Field(..., description="Whether the response is safe and tone-appropriate.")
    feedback: str = Field(..., description="Feedback on the response tone and content.")
    final_answer: str = Field(..., description="The final, possibly revised, answer to be shown to the user.")
